Repository nestjs/graphql, pull requests merged in 2019-07, with the labels that each got.

#321 perf: Lazy load ts-morph
  lib/graphql-ast.explorer.ts
  lib/graphql-definitions.factory.ts
  lib/graphql.factory.ts
Labels: enhancement

#314 Add useGlobalPrefix option
  lib/graphql.module.ts
  lib/interfaces/gql-module-options.interface.ts
  package-lock.json
  package.json
  tests/e2e/global-prefix.spec.ts
  tests/graphql/global-prefix.module.ts
Labels: enhancement

#282 bugfix: Sort file paths for more consistent type output
  lib/graphql-types.loader.ts
Labels: enhancement

#317 bugfix: correctly extend options.schema
  lib/graphql.factory.ts
Labels: bug

#260 Removing `optional` dependency
  lib/decorators/args.decorator.ts
  lib/decorators/mutation.decorator.ts
  lib/decorators/query.decorator.ts
  lib/decorators/resolver.decorator.ts
  lib/decorators/resolvers.utils.ts
  lib/decorators/subscription.decorator.ts
  package-lock.json
  package.json
Labels: enhancement, status: wip
