Repository nestjs/graphql, pull requests merged in 2020-04, with the labels that each got.

#678 GraphQL Federation - typedefs merged with typePaths
  lib/federation/graphql-federation.module.ts
Labels: enhancement

#749 Fix CustomScalar interface for strictNullChecks
  lib/interfaces/custom-scalar.interface.ts
Labels: enhancement, status: wip

#785 feat(): add additional definitions generator options
  lib/graphql-ast.explorer.ts
  lib/graphql-definitions.factory.ts
  lib/graphql.factory.ts
  lib/interfaces/gql-module-options.interface.ts
  tests/e2e/generated-definitions.spec.ts
  tests/generated-definitions/query-skip-args.fixture.ts
  tests/generated-definitions/typename.fixture.ts
  tests/generated-definitions/typename.graphql
Labels: feature

#783 feat(): add complexity feature
  lib/decorators/field.decorator.ts
  lib/decorators/resolve-field.decorator.ts
  lib/interfaces/complexity.interface.ts
  lib/interfaces/index.ts
  lib/schema-builder/factories/object-type-definition.factory.ts
  lib/schema-builder/factories/root-type.factory.ts
  lib/schema-builder/metadata/property.metadata.ts
  lib/schema-builder/metadata/resolver.metadata.ts
  lib/schema-builder/storages/type-metadata.storage.ts
Labels: feature

#776 feat(@nestjs/graphql): add mixin type helper
  lib/type-helpers/index.ts
  lib/type-helpers/intersection-type.helper.ts
Labels: enhancement

#782 feat(): use request context id symbol, attach to ctx
  lib/services/resolvers-explorer.service.ts
  lib/utils/merge-defaults.util.ts
Labels: bug, enhancement
