Repository nestjs/graphql, pull requests merged in 2021-03, with the labels that each got.

#855 style(): fix generated header comment linting
  lib/graphql.constants.ts
  tests/generated-definitions/array-property.fixture.ts
  tests/generated-definitions/custom-scalar.fixture.ts
  tests/generated-definitions/enum.fixture.ts
  tests/generated-definitions/federation.fixture.ts
  tests/generated-definitions/interface-property.fixture.ts
  tests/generated-definitions/mutation.fixture.ts
  tests/generated-definitions/query-skip-args.fixture.ts
  tests/generated-definitions/query.fixture.ts
  tests/generated-definitions/simple-type.fixture.ts
  tests/generated-definitions/typename.fixture.ts
Labels: blocked, enhancement, status: done

#1142 fix(ast): correctly mark fields as nullable when not required
  lib/graphql-ast.explorer.ts
  tests/generated-definitions/array-property.fixture.ts
  tests/generated-definitions/custom-header.fixture.ts
  tests/generated-definitions/custom-scalar-default-type.fixture.ts
  tests/generated-definitions/custom-scalar-type-mapping.fixture.ts
  tests/generated-definitions/custom-scalar.fixture.ts
  tests/generated-definitions/enum.fixture.ts
  tests/generated-definitions/federation.fixture.ts
  tests/generated-definitions/interface-property.fixture.ts
  tests/generated-definitions/mutation.fixture.ts
  tests/generated-definitions/query-skip-args.fixture.ts
  tests/generated-definitions/query.fixture.ts
  tests/generated-definitions/simple-type.fixture.ts
  tests/generated-definitions/typename.fixture.ts
Labels: enhancement

#1444 fix(federation): override federated resolveType for interfaces
  lib/federation/graphql-federation.factory.ts
  lib/schema-builder/factories/interface-definition.factory.ts
  tests/code-first-federation/app.module.ts
  tests/code-first-federation/recipe/irecipe.resolver.ts
  tests/code-first-federation/recipe/recipe.module.ts
  tests/code-first-federation/recipe/recipe.ts
  tests/e2e/code-first-federation.spec.ts
Labels: status: wip
