Repository nestjs/graphql, pull requests merged in 2022-09, with the labels that each got.

#1757 New features for GraphQL typescript plugin
  .prettierignore
  packages/graphql/lib/plugin/merge-options.ts
  packages/graphql/lib/plugin/utils/ast-utils.ts
  packages/graphql/lib/plugin/utils/plugin-utils.ts
  packages/graphql/lib/plugin/visitors/model-class.visitor.ts
  packages/graphql/lib/type-factories/create-union-type.factory.ts
  packages/graphql/lib/type-factories/register-enum-type.factory.ts
  packages/graphql/tests/plugin/cases/.gitignore
  packages/graphql/tests/plugin/cases/es5-eager-imports/author.model.ts
  packages/graphql/tests/plugin/cases/es5-eager-imports/expected/author.model.js
  packages/graphql/tests/plugin/cases/es5-eager-imports/expected/post.model.js
  packages/graphql/tests/plugin/cases/es5-eager-imports/post.model.ts
  packages/graphql/tests/plugin/cases/tsconfig.json
  packages/graphql/tests/plugin/fixtures/create-cat-alt.dto.ts
  packages/graphql/tests/plugin/fixtures/create-cat.dto.ts
  packages/graphql/tests/plugin/fixtures/deprecation.dto.ts
  packages/graphql/tests/plugin/fixtures/es5-class.dto.ts
  packages/graphql/tests/plugin/fixtures/nullable.dto.ts
  packages/graphql/tests/plugin/model-class-visitor.spec.ts
  packages/graphql/tests/plugin/plugin-utils.spec.ts
  packages/graphql/tsconfig.spec.json
Labels: feature

#2367 refactor: remove lodash usage
  packages/mercurius/lib/utils/build-mercurius-federated-schema.util.ts
Labels: mercurius, refactor

#2353 fix(schema-first): merge duplicate IQuery interface
  packages/apollo/tests/e2e/generated-definitions.spec.ts
  packages/apollo/tests/generated-definitions/federation-partial-query.fixture.ts
  packages/apollo/tests/generated-definitions/federation-partial-query.graphql
  packages/graphql/lib/federation/graphql-federation-definitions.factory.ts
Labels: bug

#2314 fix: Restrict subscriptions WS server to add listeners only to its own path
  packages/graphql/lib/services/gql-subscription.service.ts
Labels: bug
