Repository nestjs/graphql, pull requests merged in 2024-07, with the labels that each got.

#3222 feat(graphql): add support for option newline at the end of schema file
  packages/apollo/tests/e2e/graphql-sort-auto-schema.spec.ts
  packages/apollo/tests/graphql/sort-auto-schema.module.ts
  packages/graphql/lib/graphql-schema.builder.ts
  packages/graphql/lib/graphql.constants.ts
  packages/graphql/lib/interfaces/build-schema-options.interface.ts
Labels: enhancement

#3219 fix(graphql): ensure scalarsMap in buildSchemaOptions is respected
  packages/graphql/lib/graphql-schema.builder.ts
Labels: bug

#3203 feat(mercurius): upgrade to mercurius v14
  packages/mercurius/lib/drivers/mercurius-gateway.driver.ts
  packages/mercurius/package.json
  yarn.lock
Labels: dependencies

#3171 fix(apollo): federation interface resolver
  packages/apollo/tests/code-first-federation/app.module.ts
  packages/apollo/tests/code-first-federation/human/character.entity.ts
  packages/apollo/tests/code-first-federation/human/human.entity.ts
  packages/apollo/tests/code-first-federation/human/human.module.ts
  packages/apollo/tests/code-first-federation/human/human.resolver.ts
  packages/apollo/tests/e2e/__snapshots__/code-first-federation.spec.ts.snap
  packages/apollo/tests/e2e/code-first-federation.spec.ts
  packages/graphql/lib/federation/graphql-federation.factory.ts
Labels: bug

#3157 fix(graphql): add deprecationReason to ArgsOptions
  packages/graphql/lib/decorators/args.decorator.ts
  packages/graphql/lib/schema-builder/factories/args.factory.ts
  packages/graphql/lib/schema-builder/metadata/param.metadata.ts
Labels: bug
